/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'ubuntu' at '6/24/16 6:40 AM' with Gradle 2.14
 *
 * @author ubuntu, @date 6/24/16 6:40 AM
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
