/*
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'ubuntu' at '6/24/16 6:40 AM' with Gradle 2.14
 *
 * @author ubuntu, @date 6/24/16 6:40 AM
 */

import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends FunSuite {
  test("someLibraryMethod is always true") {
    def library = new Library()
    assert(library.someLibraryMethod)
  }
}
